[book]
authors = ["Ben Sully"]
language = "en"
src = "src"
title = "augurs - a time series toolkit"

[rust]
edition = "2021"

[preprocessor.langtabs]
command = "mdbook-langtabs"

[output.html]
additional-css = ["langtabs.css"]
additional-js = ["langtabs.js"]
